-- ═══════════════════════════════════════════════════════════════════════════
-- THE TREASURY — deposits, withdrawals, escrow and disputes.
--
-- ── WHAT THIS SCHEMA ASSUMES ────────────────────────────────────────────────
-- Ascend is NOT custodial today (src/lib/treasury.ts, TREASURY.custodial =
-- false). Holding a spendable customer balance is deposit-taking, which
-- engages the Banks Act, and paying it out engages the FIC Act's customer
-- due-diligence duties. Neither is a schema problem.
--
-- So every row here records an INTENT and its reconciliation against a real
-- bank statement. Nothing in this file can initiate a payment, and no state
-- transition here moves money. The state machines are complete, so the day the
-- licence exists the flag flips and this schema is already correct.
--
-- ── HOW STATE IS PROTECTED ──────────────────────────────────────────────────
-- A user may CREATE a deposit, a withdrawal request and a dispute, and may
-- READ their own. A user may NOT update state: there is no UPDATE policy on
-- any table in this file. The two state changes a user is genuinely entitled
-- to — cancelling their own withdrawal, withdrawing their own dispute — are
-- SECURITY DEFINER RPCs that validate the transition, rather than an UPDATE
-- policy that would also let them write 'paid'.
--
-- ── ON ACCOUNT DELETION ─────────────────────────────────────────────────────
-- Every table cascades from profiles(id), so delete_my_account() clears them
-- and supabase/tests/audit.test.sql keeps checking that.
--
-- There is a real tension here worth naming rather than discovering later: the
-- FIC Act requires financial records to be retained for five years, and POPIA
-- permits retention where another law requires it. Resolving that properly
-- means retaining a de-identified statutory record separate from the profile —
-- which is part of the same compliance review that is already blocking
-- automated money movement, not something to improvise in a migration. Until
-- that review happens, deletion wins, because that is the promise the product
-- currently makes to the person.
-- ═══════════════════════════════════════════════════════════════════════════

set check_function_bodies = off;

-- ─────────────────────────────────────────────────────────────────────────────
-- deposits — money coming in
--
-- The reference is generated by a trigger, never supplied by the client. A
-- client that could choose its own reference could claim somebody else's
-- incoming EFT by guessing theirs.
-- ─────────────────────────────────────────────────────────────────────────────
create table public.deposits (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles(id) on delete cascade,
  amount      numeric(12,2) not null check (amount >= 50 and amount <= 50000),
  currency    char(3) not null default 'ZAR' check (currency = 'ZAR'),
  state       text not null default 'instructed' check (state in (
                'instructed','awaiting_transfer','received',
                'reconciled','credited','failed','refunded'
              )),
  -- Per-user counter, so a reference is reproducible if the user loses the
  -- screen instead of being reissued and splitting one payment across two rows.
  sequence    int not null,
  reference   text not null,
  -- Filled by an operator from the bank statement line that matched.
  bank_reference text,
  reconciled_at  timestamptz,
  failure_reason text,
  created_at  timestamptz not null default now(),
  unique (user_id, sequence),
  unique (reference)
);

-- The reference: ASC + 5 chars from a hash of the user id + 2-digit sequence.
-- Mirrors depositReference() in src/lib/treasury.ts so the value the UI shows
-- before insert is the value that gets stored.
create or replace function public.deposit_reference(_user_id uuid, _sequence int)
returns text
language plpgsql
immutable
as $$
declare
  alphabet constant text := 'ABCDEFGHJKMNPQRSTUVWXYZ23456789'; -- no I, L, O, 0, 1
  h  bigint := 2166136261;      -- FNV-1a offset basis
  s  text   := _user_id::text;
  body text := '';
  i  int;
begin
  for i in 1..length(s) loop
    h := (h # ascii(substr(s, i, 1)))::bigint;
    h := (h * 16777619) & 4294967295;   -- 32-bit FNV prime, wrapped
  end loop;
  for i in 1..5 loop
    body := body || substr(alphabet, (h % 31)::int + 1, 1);
    h := h / 31;
  end loop;
  return 'ASC' || body || lpad(_sequence::text, 2, '0');
end;
$$;

create or replace function public.deposits_set_reference()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- The client's own values for these are ignored on purpose.
  new.sequence  := coalesce(
    (select max(d.sequence) + 1 from public.deposits d where d.user_id = new.user_id), 1);
  new.reference := public.deposit_reference(new.user_id, new.sequence);
  new.state     := 'instructed';
  return new;
end;
$$;

create trigger deposits_reference before insert on public.deposits
  for each row execute function public.deposits_set_reference();

alter table public.deposits enable row level security;

create policy deposits_select_own on public.deposits
  for select using (user_id = auth.uid());
-- A user may declare an intent to pay. They may not declare that it arrived:
-- the trigger forces state back to 'instructed' on every insert.
create policy deposits_insert_own on public.deposits
  for insert with check (user_id = auth.uid());
-- Deliberately no UPDATE and no DELETE policy. State moves only through the
-- reconciliation job, and a deposit record is evidence.

create index deposits_user_idx on public.deposits (user_id, created_at desc);
create index deposits_open_idx on public.deposits (state)
  where state in ('instructed','awaiting_transfer','received');

create table public.deposit_events (
  id         uuid primary key default gen_random_uuid(),
  deposit_id uuid not null references public.deposits(id) on delete cascade,
  user_id    uuid not null references public.profiles(id) on delete cascade,
  from_state text,
  to_state   text not null,
  reason     text not null,
  actor      text not null default 'system' check (actor in ('system','operator','user')),
  created_at timestamptz not null default now()
);
alter table public.deposit_events enable row level security;

create policy deposit_events_select_own on public.deposit_events
  for select using (user_id = auth.uid());

create index deposit_events_deposit_idx on public.deposit_events (deposit_id, created_at);

-- ─────────────────────────────────────────────────────────────────────────────
-- withdrawals — money going out
--
-- amount_requested is what the person asked for; amount_paid is what actually
-- landed. They are separate columns because a bank fee or a partial payment
-- makes them differ, and overwriting the request with the outcome destroys the
-- only record of what was promised.
-- ─────────────────────────────────────────────────────────────────────────────
create table public.withdrawals (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null references public.profiles(id) on delete cascade,
  destination_id uuid references public.payout_destinations(id) on delete set null,
  amount_requested numeric(12,2) not null check (amount_requested >= 50),
  amount_paid      numeric(12,2),
  currency       char(3) not null default 'ZAR' check (currency = 'ZAR'),
  state          text not null default 'requested' check (state in (
                   'requested','verification','approved','scheduled',
                   'submitted','paid','rejected','cancelled'
                 )),
  -- The payment run this is queued into, from nextPayoutRun().
  scheduled_for  date,
  bank_reference text,
  -- Shown verbatim to the person. A rejection with no reason is not a decision,
  -- it is a wall.
  decision_reason text,
  requested_at   timestamptz not null default now(),
  settled_at     timestamptz
);

-- A client that could insert state = 'approved' would have approved its own
-- withdrawal. Force the entry state on the way in.
create or replace function public.withdrawals_force_initial_state()
returns trigger
language plpgsql
as $$
begin
  new.state       := 'requested';
  new.amount_paid := null;
  new.settled_at  := null;
  return new;
end;
$$;

create trigger withdrawals_initial_state before insert on public.withdrawals
  for each row execute function public.withdrawals_force_initial_state();

alter table public.withdrawals enable row level security;

create policy withdrawals_select_own on public.withdrawals
  for select using (user_id = auth.uid());
create policy withdrawals_insert_own on public.withdrawals
  for insert with check (
    user_id = auth.uid()
    -- You may only be paid into an account you own and that has been verified.
    and (
      destination_id is null
      or exists (
        select 1 from public.payout_destinations d
        where d.id = destination_id and d.user_id = auth.uid() and d.verified
      )
    )
  );
-- No UPDATE policy. Cancellation goes through cancel_my_withdrawal() below.

create index withdrawals_user_idx on public.withdrawals (user_id, requested_at desc);
create index withdrawals_run_idx  on public.withdrawals (scheduled_for)
  where state in ('approved','scheduled');

create table public.withdrawal_events (
  id            uuid primary key default gen_random_uuid(),
  withdrawal_id uuid not null references public.withdrawals(id) on delete cascade,
  user_id       uuid not null references public.profiles(id) on delete cascade,
  from_state    text,
  to_state      text not null,
  reason        text not null,
  actor         text not null default 'system' check (actor in ('system','operator','user')),
  created_at    timestamptz not null default now()
);
alter table public.withdrawal_events enable row level security;

create policy withdrawal_events_select_own on public.withdrawal_events
  for select using (user_id = auth.uid());

create index withdrawal_events_w_idx on public.withdrawal_events (withdrawal_id, created_at);

-- ─────────────────────────────────────────────────────────────────────────────
-- cancel_my_withdrawal — the one state change a user owns
--
-- SECURITY DEFINER so it can write a table with no UPDATE policy, and scoped to
-- auth.uid() in the WHERE clause so the id argument cannot reach anybody else's
-- row. The allowed-from list is the same whitelist as WITHDRAWAL_NEXT: once the
-- instruction has been submitted to the bank there is nothing left to cancel.
-- ─────────────────────────────────────────────────────────────────────────────
create or replace function public.cancel_my_withdrawal(_withdrawal_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  prev text;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated.';
  end if;

  select state into prev
  from public.withdrawals
  where id = _withdrawal_id and user_id = auth.uid()
  for update;

  if prev is null then
    raise exception 'No such withdrawal.';
  end if;
  if prev not in ('requested','verification','approved','scheduled') then
    raise exception 'A withdrawal that is % can no longer be cancelled.', prev;
  end if;

  update public.withdrawals
     set state = 'cancelled', settled_at = now()
   where id = _withdrawal_id and user_id = auth.uid();

  insert into public.withdrawal_events (withdrawal_id, user_id, from_state, to_state, reason, actor)
  values (_withdrawal_id, auth.uid(), prev, 'cancelled', 'Cancelled by the account holder.', 'user');
end;
$$;

revoke execute on function public.cancel_my_withdrawal(uuid) from public, anon;
grant  execute on function public.cancel_my_withdrawal(uuid) to authenticated;

-- ─────────────────────────────────────────────────────────────────────────────
-- escrow_holds — a stake held against an undecided outcome
--
-- released_to is null while the outcome is open. The fee is stored alongside
-- the split so a settlement can be re-read years later without re-deriving it
-- from whatever the fee rate happens to be then.
-- ─────────────────────────────────────────────────────────────────────────────
create table public.escrow_holds (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles(id) on delete cascade,
  stake_id    uuid not null references public.stakes(id) on delete cascade,
  cohort_id   uuid not null references public.stake_cohorts(id) on delete cascade,
  amount      numeric(12,2) not null check (amount > 0),
  released_to text check (released_to in ('user','pool')),
  amount_to_user numeric(12,2) check (amount_to_user >= 0),
  amount_to_pool numeric(12,2) check (amount_to_pool >= 0),
  fee            numeric(12,2) check (fee >= 0),
  placed_on   date not null default (now() at time zone 'utc')::date,
  released_at timestamptz,
  -- Either it is open, or it is fully accounted for. No half-settled rows.
  constraint escrow_settled_consistently check (
    (released_to is null
      and amount_to_user is null and amount_to_pool is null and fee is null and released_at is null)
    or
    (released_to is not null
      and amount_to_user is not null and amount_to_pool is not null and fee is not null
      and released_at is not null
      and amount_to_user + amount_to_pool + fee = amount)
  ),
  unique (stake_id)
);
alter table public.escrow_holds enable row level security;

-- Owner-only, exactly like stakes. An escrow amount is a stake amount by
-- another name, and stakes.amount is never visible to another user.
create policy escrow_holds_select_own on public.escrow_holds
  for select using (user_id = auth.uid());
-- Written by the settlement job only: a hold the user could create or release
-- is not a hold.

create index escrow_holds_user_idx on public.escrow_holds (user_id, placed_on desc);
create index escrow_holds_open_idx on public.escrow_holds (cohort_id) where released_to is null;

-- ─────────────────────────────────────────────────────────────────────────────
-- disputes — sixty days to say "this is wrong"
-- ─────────────────────────────────────────────────────────────────────────────
create table public.disputes (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles(id) on delete cascade,
  -- What is being disputed. Exactly one of these is set.
  cohort_id     uuid references public.stake_cohorts(id) on delete set null,
  payout_id     uuid references public.payouts(id) on delete set null,
  withdrawal_id uuid references public.withdrawals(id) on delete set null,
  deposit_id    uuid references public.deposits(id) on delete set null,
  state       text not null default 'open' check (state in (
                'open','evidence','review','upheld','declined','withdrawn'
              )),
  category    text not null check (category in (
                'verification_rejected','payout_amount','payout_missing',
                'deposit_missing','settlement_outcome','other'
              )),
  summary     text not null check (length(summary) between 10 and 2000),
  -- Written by the reviewer, shown to the person. Same rule as a rejection.
  resolution  text,
  opened_at   timestamptz not null default now(),
  resolved_at timestamptz,
  constraint dispute_names_one_subject check (
    (cohort_id is not null)::int + (payout_id is not null)::int
    + (withdrawal_id is not null)::int + (deposit_id is not null)::int = 1
  )
);

create or replace function public.disputes_force_initial_state()
returns trigger
language plpgsql
as $$
begin
  new.state       := 'open';
  new.resolution  := null;
  new.resolved_at := null;
  return new;
end;
$$;

create trigger disputes_initial_state before insert on public.disputes
  for each row execute function public.disputes_force_initial_state();

alter table public.disputes enable row level security;

create policy disputes_select_own on public.disputes
  for select using (user_id = auth.uid());
create policy disputes_insert_own on public.disputes
  for insert with check (user_id = auth.uid());
-- No UPDATE policy: a person who could set their own dispute to 'upheld' has
-- not raised a dispute, they have written a decision.

create index disputes_user_idx on public.disputes (user_id, opened_at desc);
create index disputes_open_idx on public.disputes (state)
  where state in ('open','evidence','review');

create table public.dispute_messages (
  id         uuid primary key default gen_random_uuid(),
  dispute_id uuid not null references public.disputes(id) on delete cascade,
  user_id    uuid not null references public.profiles(id) on delete cascade,
  author     text not null check (author in ('user','support')),
  body       text not null check (length(body) between 1 and 4000),
  created_at timestamptz not null default now()
);
alter table public.dispute_messages enable row level security;

create policy dispute_messages_select_own on public.dispute_messages
  for select using (user_id = auth.uid());
-- A user may add to their own dispute, but only as themselves. Without the
-- author check a user could post a message attributed to support and then
-- screenshot it.
create policy dispute_messages_insert_own on public.dispute_messages
  for insert with check (
    user_id = auth.uid()
    and author = 'user'
    and exists (
      select 1 from public.disputes d
      where d.id = dispute_id and d.user_id = auth.uid()
        and d.state in ('open','evidence')
    )
  );

create index dispute_messages_dispute_idx on public.dispute_messages (dispute_id, created_at);

-- ─────────────────────────────────────────────────────────────────────────────
-- withdraw_my_dispute — the user's own exit, up to the point of review
-- ─────────────────────────────────────────────────────────────────────────────
create or replace function public.withdraw_my_dispute(_dispute_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  prev text;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated.';
  end if;

  select state into prev
  from public.disputes
  where id = _dispute_id and user_id = auth.uid()
  for update;

  if prev is null then
    raise exception 'No such dispute.';
  end if;
  if prev not in ('open','evidence') then
    raise exception 'A dispute that is % can no longer be withdrawn.', prev;
  end if;

  update public.disputes
     set state = 'withdrawn', resolved_at = now()
   where id = _dispute_id and user_id = auth.uid();
end;
$$;

revoke execute on function public.withdraw_my_dispute(uuid) from public, anon;
grant  execute on function public.withdraw_my_dispute(uuid) to authenticated;

-- ═════════════════════════════════════════════════════════════════════════════
-- treasury_balances() — the nine buckets, for the caller and nobody else.
--
-- DERIVED, never stored. A stored balance is a number that can drift from the
-- ledger that is supposed to explain it, and when they disagree there is no
-- way to know which one is lying. Deriving costs a query and buys the property
-- that the total always equals the sum of its evidence.
--
-- Takes no arguments, so there is no user id an attacker could substitute.
-- ═════════════════════════════════════════════════════════════════════════════
create or replace function public.treasury_balances()
returns table (
  available         numeric,
  pending           numeric,
  locked            numeric,
  escrow            numeric,
  processing        numeric,
  verification_hold numeric,
  rewards           numeric,
  referral          numeric,
  withdrawable      numeric
)
language sql
stable
security definer
set search_path = public
as $$
  with me as (select auth.uid() as uid),
  dep as (
    select
      coalesce(sum(amount) filter (where state = 'credited'), 0)  as credited,
      coalesce(sum(amount) filter (
        where state in ('instructed','awaiting_transfer','received','reconciled')), 0) as inflight
    from public.deposits, me where user_id = me.uid
  ),
  esc as (
    select coalesce(sum(amount) filter (where released_to is null), 0) as open_escrow
    from public.escrow_holds, me where user_id = me.uid
  ),
  live as (
    select coalesce(sum(s.amount) filter (where s.payment_confirmed), 0) as locked
    from public.stakes s
    join public.stake_cohorts c on c.id = s.cohort_id
    cross join me
    where s.user_id = me.uid and c.status in ('open','active')
  ),
  wd as (
    select
      coalesce(sum(amount_requested) filter (
        where state in ('approved','scheduled','submitted')), 0) as processing,
      coalesce(sum(amount_requested) filter (
        where state in ('requested','verification')), 0) as awaiting
    from public.withdrawals, me where user_id = me.uid
  ),
  hold as (
    -- Money a payout is holding back while an integrity review runs.
    select coalesce(sum(p.amount) filter (
             where p.status in ('fraud_review','manual_review','pending_verification')), 0) as held,
           coalesce(sum(p.amount) filter (where p.status = 'paid'), 0)  as paid,
           coalesce(sum(p.amount) filter (
             where p.status in ('verified','queued','scheduled')), 0)   as ready
    from public.payouts p cross join me where p.user_id = me.uid
  ),
  ref as (
    select coalesce(sum(amount) filter (where kind = 'winnings_credited'), 0) as rewards
    from public.wallet_transactions, me
    where user_id = me.uid and status = 'cleared'
  )
  select
    greatest(dep.credited - esc.open_escrow - wd.processing - wd.awaiting, 0),
    dep.inflight,
    live.locked,
    esc.open_escrow,
    wd.processing,
    hold.held,
    ref.rewards,
    0::numeric,   -- referral earnings: the referral ledger lands with that feature
    greatest(hold.ready + greatest(dep.credited - esc.open_escrow, 0)
             - wd.processing - wd.awaiting, 0)
  from dep, esc, live, wd, hold, ref;
$$;

revoke execute on function public.treasury_balances() from public, anon;
grant  execute on function public.treasury_balances() to authenticated;

-- deposit_reference is pure arithmetic on values the caller already has; it is
-- exposed so the UI can show the reference before the row exists.
grant execute on function public.deposit_reference(uuid, int) to authenticated;
